### PR TITLE
Python2.7

### PR DESCRIPTION
**Pull request by tardyp**
as suggested by @rodrigc in https://github.com/buildbot/buildbot/issues/4439

shot

### CODE REVIEW

**Comment by rodrigc** [comment]
I think the is the right place for this.  But I would recommend that you make this message more scary.

For example:
* use red colors
* put an icon with a warning sign
* use text something like "Buildbot is dropping support for Python 2.7.  Users are encouraged to migrate to Python 3 ASAP"
*

**Comment by p12tic** [comment]
>  But I would recommend that you make this message more scary.

+1

If the plan is still to drop it at v2.0, ASAP is the right wording.

**Comment by tardyp** [comment]
updated code and screenshot as per review

**Comment by tardyp** [comment]
deployed in http://buildbot.net/

**Pull request merged**
